### ISSUE TITLE
authorization, widgetId 값을 가져오는 방법이 궁금합니다.

### ISSUE THREAD

**Issue by GalaxyGiant** [bsy0317/SKT-IoT-API#1]
authorization, widgetId 값은 Packet Capture를 통해 얻을 수 있습니다.

NUGU 스마트홈에서 얻은 authorization Key
NUGU 스마트홈에서 얻은 widgetId Value

라고 되어 있는데..
Packet Capture 앱을 어떻게 사용해야 값을 가져올 수 있는지 모르겠습니다...ㅠㅠ

**Comment by bsy0318** [comment]
비슷한 내용으로 아래의 Repository Readme에 설명한 내용이 있습니다.
참고하여 해보시고 어렵다면 다시 남겨주세요!
[Dawon-PowerManager Readme](https://github.com/bsy0317/Dawon-PowerManager/blob/main/readme.md)

**Comment by GalaxyGiant** [comment]
> 비슷한 내용으로 아래의 Repository Readme에 설명한 내용이 있습니다. 참고하여 해보시고 어렵다면 다시 남겨주세요! [Dawon-PowerManager Readme](https://github.com/bsy0317/Dawon-PowerManager/blob/main/readme.md)

감사합니다. ios 버전으로 해결했습니다!
