### ISSUE TITLE
실행시 오류가 발생합니다. config['Credentials']...

### ISSUE THREAD

**Issue by GalaxyGiant** [bsy0317/SKT-IoT-API#2]
알려주신 방법으로 authorization 값과 rtnDvcId 코드를 수정해서 실행했는데 오류가 발생합니다 ㅠㅠ

![image](https://github.com/bsy0317/SKT-IoT-API/assets/24563566/41fb47cb-a87a-4291-9a0d-9d25457e7bc0)

어떤 부분이 문제일까요..? 

제가 authorization 값을 잘못된 것을 입력했나 생각도 듭니다.

rtnDvcld 값은 예제와 같은 길이로 있었는데 authorization 값은 15자리의 예제와 달리 저는 

vXXbbb88bX6Xb0XbXbXnXb3Xbb9I85fXXXXlXrX1511Xf2xkXXXXXr/bS5bX1X4p 

이런 형태의 값이 있어서 이대로 입력했었습니다. (끝에 / 도 있었습니다.)
이 값을 잘못 넣어서 오류가 발생한 것일까요..?

**Comment by bsy0318** [comment]
아니요. 길이는 상관이없습니다. settings.ini의 문법이 잘못된 것 같습니다. 띄어쓰기도 영향을 받으니 다시 확인해보세요! Auth 키 오류는 아닙니다

**Comment by GalaxyGiant** [comment]
> 아니요. 길이는 상관이없습니다. settings.ini의 문법이 잘못된 것 같습니다. 띄어쓰기도 영향을 받으니 다시 확인해보세요! Auth 키 오류는 아닙니다

{"message":"\uc131\uacf5","resultCd":"off"}

settings_sample.ini 파일을 그대로 쓴게 문제였습니다 ㅠㅠㅎ 답변주신 내용을 곰곰히 생각해보다가 파일명이 다른것 같아 사용법을 재차 확인 후 카피해서  settings.ini 파일로 만들었더니 바로 성공했습니다!! 
정말 좋은 것을 만들어주셔서 감사합니다.
이걸 이제 HA에서 어떻게 실행 후 명령어를 호출해야할지 다시 찾아봐야겠습니다....!

**Comment by bsy0318** [comment]
HB에서는 homebridge-http-iot 플러그인으로 쉽게 사용가능합니다. HA에서 비슷한 플러그인 찾아보세용
